/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_WALLET_BINDINGS__
#define __RUST_WALLET_BINDINGS__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

typedef struct {
    uint8_t idx[32];
} uint8_32_array_t;

/** \brief
 *  Wrapper for orchard signing key
 */
typedef struct SigningKey {
    /** <No documentation available> */
    uint8_32_array_t bytes;
} SigningKey_t;

/** <No documentation available> */
SigningKey_t
new_signing_key (void);

/** \brief
 *  Like [`slice_ref`] and [`slice_mut`], but with any lifetime attached
 *  whatsoever.
 *
 *  It is only intended to be used as the parameter of a **callback** that
 *  locally borrows it, due to limitations of the [`ReprC`][
 *  `trait@crate::layout::ReprC`] design _w.r.t._ higher-rank trait bounds.
 *
 *  # C layout (for some given type T)
 *
 *  ```c
 *  typedef struct {
 *  // Cannot be NULL
 *  T * ptr;
 *  size_t len;
 *  } slice_T;
 *  ```
 *
 *  # Nullable pointer?
 *
 *  If you want to support the above typedef, but where the `ptr` field is
 *  allowed to be `NULL` (with the contents of `len` then being undefined)
 *  use the `Option< slice_ptr<_> >` type.
 */
typedef struct slice_raw_uint8 {
    /** \brief
     *  Pointer to the first element (if any).
     */
    uint8_t * ptr;

    /** \brief
     *  Element count
     */
    size_t len;
} slice_raw_uint8_t;

typedef struct {
    uint8_t idx[64];
} uint8_64_array_t;

/** <No documentation available> */
typedef struct Signature {
    /** <No documentation available> */
    uint8_64_array_t bytes;
} Signature_t;

/** <No documentation available> */
int32_t
sign_message (
    SigningKey_t sk,
    slice_raw_uint8_t msg,
    Signature_t * sig);

/** <No documentation available> */
typedef struct VerificationKey {
    /** <No documentation available> */
    uint8_32_array_t bytes;
} VerificationKey_t;

/** <No documentation available> */
int32_t
verification_key (
    SigningKey_t const * sk,
    VerificationKey_t * vk);

/** <No documentation available> */
int32_t
verify (
    VerificationKey_t pk,
    slice_raw_uint8_t msg,
    Signature_t const * signature);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_WALLET_BINDINGS__ */
