/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_WALLET_BINDINGS__
#define __RUST_WALLET_BINDINGS__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_uint8 {
    /** <No documentation available> */
    uint8_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_uint8_t;

typedef struct {
    uint8_t idx[32];
} uint8_32_array_t;

/** <No documentation available> */
typedef struct IdentifiedData_Vec_uint8 {
    /** <No documentation available> */
    uint8_32_array_t identifier;

    /** <No documentation available> */
    Vec_uint8_t data;
} IdentifiedData_Vec_uint8_t;

/** <No documentation available> */
int32_t
frost_dkg_part1 (
    uint16_t participant_identifier,
    uint16_t max_signers,
    uint16_t min_signers,
    Vec_uint8_t * round1_secret_package,
    IdentifiedData_Vec_uint8_t * round1_package);

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_IdentifiedData_Vec_uint8 {
    /** <No documentation available> */
    IdentifiedData_Vec_uint8_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_IdentifiedData_Vec_uint8_t;

/** <No documentation available> */
int32_t
frost_dkg_part2 (
    Vec_uint8_t const * round1_secret_package,
    Vec_IdentifiedData_Vec_uint8_t const * round1_packages,
    Vec_uint8_t * round2_secret_package,
    Vec_IdentifiedData_Vec_uint8_t * round2_packages);

/** <No documentation available> */
typedef struct KeyPackage {
    /** <No documentation available> */
    Vec_uint8_t bytes;
} KeyPackage_t;

/** <No documentation available> */
typedef struct IdentifiedData_KeyPackage {
    /** <No documentation available> */
    uint8_32_array_t identifier;

    /** <No documentation available> */
    KeyPackage_t data;
} IdentifiedData_KeyPackage_t;

/** <No documentation available> */
int32_t
frost_dkg_part3 (
    Vec_uint8_t const * round2_secret_package,
    Vec_IdentifiedData_Vec_uint8_t const * round1_packages,
    Vec_IdentifiedData_Vec_uint8_t const * round2_packages,
    IdentifiedData_KeyPackage_t * key_package,
    Vec_uint8_t * pubkey_package);

/** \brief
 *  Round2: Generate user's signature share.
 */
int32_t
frost_randomized_aggregate (
    Vec_uint8_t const * signing_package,
    Vec_IdentifiedData_Vec_uint8_t const * signature_shares,
    Vec_uint8_t const * pubkeys,
    uint8_32_array_t const * randomizer,
    Vec_uint8_t * signature);

/** \brief
 *  Round1: Generate one nonce and one `SigningCommitments`` instance for each participant.
 */
int32_t
frost_randomized_commit (
    uint16_t identifier,
    KeyPackage_t const * key_package,
    Vec_uint8_t * signing_nonces,
    Vec_uint8_t * signing_commitments,
    IdentifiedData_Vec_uint8_t * identified_signing_commitments);

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_IdentifiedData_KeyPackage {
    /** <No documentation available> */
    IdentifiedData_KeyPackage_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_IdentifiedData_KeyPackage_t;

/** \brief
 *  Wrapper for orchard signing key
 */
typedef struct TrustedShares {
    /** <No documentation available> */
    Vec_IdentifiedData_KeyPackage_t key_packages;

    /** <No documentation available> */
    Vec_uint8_t public_key_package;
} TrustedShares_t;

/** <No documentation available> */
int32_t
frost_randomized_keygen_dealer (
    uint16_t max_signers,
    uint16_t min_signers,
    TrustedShares_t * trusted_share);

/** \brief
 *  Generate new `randomizer`.
 */
uint8_32_array_t
frost_randomized_new_randomizer (void);

/** \brief
 *  Round2: Generate user's signature share.
 */
int32_t
frost_randomized_sign_package (
    Vec_uint8_t const * signing_package,
    Vec_uint8_t const * nonces_to_use,
    KeyPackage_t const * key_package,
    uint8_32_array_t const * randomizer,
    Vec_uint8_t * signature_share,
    IdentifiedData_Vec_uint8_t * identified_signature_share);

/** \brief
 *  Like [`slice_ref`] and [`slice_mut`], but with any lifetime attached
 *  whatsoever.
 *
 *  It is only intended to be used as the parameter of a **callback** that
 *  locally borrows it, due to limitations of the [`ReprC`][
 *  `trait@crate::layout::ReprC`] design _w.r.t._ higher-rank trait bounds.
 *
 *  # C layout (for some given type T)
 *
 *  ```c
 *  typedef struct {
 *  // Cannot be NULL
 *  T * ptr;
 *  size_t len;
 *  } slice_T;
 *  ```
 *
 *  # Nullable pointer?
 *
 *  If you want to support the above typedef, but where the `ptr` field is
 *  allowed to be `NULL` (with the contents of `len` then being undefined)
 *  use the `Option< slice_ptr<_> >` type.
 */
typedef struct slice_raw_uint8 {
    /** \brief
     *  Pointer to the first element (if any).
     */
    uint8_t * ptr;

    /** \brief
     *  Element count
     */
    size_t len;
} slice_raw_uint8_t;

/** \brief
 *  Round1: Generate signing package for the given message and user secret share.
 */
int32_t
frost_randomized_signing_package_new (
    Vec_IdentifiedData_Vec_uint8_t signing_commitments,
    slice_raw_uint8_t message,
    Vec_uint8_t * signature_package);

/** \brief
 *  Round2: Generate user's signature share.
 */
int32_t
frost_randomized_verify (
    slice_raw_uint8_t message,
    Vec_uint8_t const * group_signature,
    Vec_uint8_t const * public_key_package,
    uint8_32_array_t const * randomizer);

/** <No documentation available> */
uint16_t
identified_data_id_as_u16 (
    IdentifiedData_Vec_uint8_t const * data);

/** <No documentation available> */
int32_t
identified_data_new_u16 (
    uint16_t id,
    Vec_uint8_t const * data,
    IdentifiedData_Vec_uint8_t * identified_data);

/** <No documentation available> */
int32_t
import_account_ufvk (void);

/** <No documentation available> */
int32_t
init_cache_db (void);

/** <No documentation available> */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum LogLevel {
    /** <No documentation available> */
    LOG_LEVEL_OFF = 0,
    /** <No documentation available> */
    LOG_LEVEL_ERROR,
    /** <No documentation available> */
    LOG_LEVEL_WARNING,
    /** <No documentation available> */
    LOG_LEVEL_INFO,
    /** <No documentation available> */
    LOG_LEVEL_DEBUG,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
LogLevel_t;

/** <No documentation available> */
void
init_rust_logging (
    LogLevel_t level);

/** \brief
 *  The enumeration of known Zcash networks.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum Network {
    /** \brief
     *  Zcash Mainnet.
     */
    NETWORK_MAIN_NETWORK = 0,
    /** \brief
     *  Zcash Testnet.
     */
    NETWORK_TEST_NETWORK,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
Network_t;

/** <No documentation available> */
int32_t
init_wallet_db (
    char const * path,
    Network_t network);

/** \brief
 *  Wrapper for orchard signing key
 */
typedef struct SigningKey {
    /** <No documentation available> */
    uint8_32_array_t bytes;
} SigningKey_t;

/** <No documentation available> */
SigningKey_t
new_signing_key (void);

/** <No documentation available> */
int32_t
read_pczt_signining_inputs (void);

/** <No documentation available> */
int32_t
run_sync (
    char const * host,
    uint16_t port,
    char const * fsblockdb_root,
    Network_t network,
    char const * db_path);

/** <No documentation available> */
int32_t
send_from_orchard (void);

typedef struct {
    uint8_t idx[64];
} uint8_64_array_t;

/** <No documentation available> */
typedef struct Signature {
    /** <No documentation available> */
    uint8_64_array_t bytes;
} Signature_t;

/** <No documentation available> */
int32_t
sign_message (
    SigningKey_t sk,
    slice_raw_uint8_t msg,
    Signature_t * sig);

/** <No documentation available> */
typedef struct VerificationKey {
    /** <No documentation available> */
    uint8_32_array_t bytes;
} VerificationKey_t;

/** <No documentation available> */
int32_t
verification_key (
    SigningKey_t const * sk,
    VerificationKey_t * vk);

/** <No documentation available> */
int32_t
verify (
    VerificationKey_t pk,
    slice_raw_uint8_t msg,
    Signature_t const * signature);

/** <No documentation available> */
int32_t
write_pczt_signing_outputs (void);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_WALLET_BINDINGS__ */
